### ISSUE TITLE
Advice about operational issues

### ISSUE THREAD

**Issue by myxingchao** [lucadentella/enc28j60_tutorial#1]
Mr.luca, I was a university student from China, read your enc28J60 and Arduino (14), I felt pretty cool, but I saw the tutorial, are not configured, can you  give me about the source and the steps it? Looking forward to your reply

**Comment by lucadentella** [comment]
the source is here on github, while a description of the tutorial is on my blog (www.lucadentella.it).

**Comment by myxingchao** [comment]
“ambientMonitor.html ”This file is placed in my server? Then arduino address points to the server?

**Comment by myxingchao** [comment]
“ambientMonitor.html ”This file is placed in my server? Then arduino address points to the server?
